daysUntilStale: 60
daysUntilClose: 7
staleLabel: wontfix
markComment: >
  Ce problème a été automatiquement marqué comme périmé car il n'a pas eu
  d’activité récente. Il sera fermé dans 7 jours si aucune autre activité ne se produit. Merci
  pour votre contribution.
closeComment: false
